version: '3.9'
services:

  ms-db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    networks:
      - ms_network
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql




volumes:
  my-db:
  db_data:

networks:
  ms_network: