spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demoproj?
    username: root #${DB_CONNECTION_USERNAME:user}
    password:  #${DB_CONNECTION_PASSWORD:password}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 752270580410-439tdi3ii62vn3lu6o9nniftsab4lsfb.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 1745572012577593
            client-secret: fcc6232a72e582ebeb37780d9866dbc3



#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: /Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/jre/lib/security/cacerts
#    key-store-password: musa2001
#    key-alias: mycert
#    enabled: false